[package]
name = "reactor_direct2d"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
windows-core = { workspace = true }
windows-reactor = { workspace = true, features = ["winui-backend"] }
windows-numerics = { workspace = true }
windows-canvas = { workspace = true }

[build-dependencies]
windows-reactor-setup = { workspace = true }
windows-bindgen = { workspace = true }

[lints]
workspace = true
