use windows_bindgen::*;

fn main() {
    let time = std::time::Instant::now();

    bindgen(["--etc", "crates/tools/bindings/src/collections.txt"]);
    bindgen(["--etc", "crates/tools/bindings/src/core.txt"]);
    bindgen(["--etc", "crates/tools/bindings/src/cppwinrt.txt"]);
    bindgen(["--etc", "crates/tools/bindings/src/future_impl.txt"]);
    bindgen(["--etc", "crates/tools/bindings/src/future.txt"]);
    bindgen(["--etc", "crates/tools/bindings/src/metadata.txt"]);
    bindgen(["--etc", "crates/tools/bindings/src/numerics.txt"]);
    bindgen(["--etc", "crates/tools/bindings/src/registry.txt"]);
    bindgen(["--etc", "crates/tools/bindings/src/result.txt"]);
    bindgen(["--etc", "crates/tools/bindings/src/strings.txt"]);
    bindgen(["--etc", "crates/tools/bindings/src/version.txt"]);
    bindgen(["--etc", "crates/tools/bindings/src/threading.txt"]);
    bindgen(["--etc", "crates/tools/bindings/src/time.txt"]);
    bindgen(["--etc", "crates/tools/bindings/src/services.txt"]);

    // The namespaces the vendored corpus does not carry, compiled from
    // `metadata/*.rdl` into a throwaway winmd that the filters below name alongside
    // `default`. See `helpers::AUTHORED_METADATA`.
    helpers::compile_authored_metadata();

    bindgen(["--etc", "crates/tools/bindings/src/canvas.txt"]);
    bindgen(["--etc", "crates/tools/bindings/src/animation.txt"]);
    bindgen(["--etc", "crates/tools/bindings/src/window.txt"]);

    bindgen(["--etc", "crates/tools/bindings/src/d2d.txt"]);
    bindgen(["--etc", "crates/tools/bindings/src/text.txt"]);
    bindgen(["--etc", "crates/tools/bindings/src/present.txt"]);
    bindgen(["--etc", "crates/tools/bindings/src/ui.txt"]);

    // The synthetic-input harness. It reads no framework crate, so it sits with the
    // other test crates and generates its own surface from the same corpus.
    bindgen(["--etc", "crates/tools/bindings/src/injector.txt"]);

    // NOTE: Reactor bindings are generated by tool_reactor.
    // WebView2 bindings are generated by tool_webview.
    // Package crates (windows, windows-sys) are generated by tool_package.

    println!("Finished in {:.2}s", time.elapsed().as_secs_f32());
}
